server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: event-config-service
  datasource:
    url: jdbc:h2:mem:eventdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /api/v1/docs/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /api/v1/docs/api-docs

# Настройки webhook
webhook:
  retry-count: 3
  retry-delay-ms: 5000
  signature-header-name: X-Webhook-Signature
  signature-algorithm: HMAC-SHA256
  asyncapi-url: /api/v1/docs/event-webhook-asyncapi.yaml
